{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "02f6b66f-f91b-4984-aa31-e04dd54e8844",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "? Loading SVM model from C:\\Users\\abina\\DietMonitoringSystem\\backend\\..\\models\\svm_model.pkl\n",
      "? Loading ResNet18 model for feature extraction\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\abina\\anaconda3\\Lib\\site-packages\\sklearn\\base.py:380: InconsistentVersionWarning: Trying to unpickle estimator SVC from version 1.4.2 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:\n",
      "https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations\n",
      "  warnings.warn(\n",
      "Using cache found in C:\\Users\\abina/.cache\\torch\\hub\\pytorch_vision_v0.10.0\n",
      "C:\\Users\\abina\\anaconda3\\Lib\\site-packages\\torchvision\\models\\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.\n",
      "  warnings.warn(\n",
      "C:\\Users\\abina\\anaconda3\\Lib\\site-packages\\torchvision\\models\\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.\n",
      "  warnings.warn(msg)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app '__main__'\n",
      " * Debug mode: on\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\n",
      " * Running on http://127.0.0.1:5000\n",
      "Press CTRL+C to quit\n",
      "127.0.0.1 - - [24/Apr/2025 14:20:54] \"GET / HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:20:54] \"GET /assets/food-bg.jpg HTTP/1.1\" 404 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:21:06] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:21:27] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:21:51] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:22:04] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:27:09] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:29:05] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:31:22] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:33:36] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:45:22] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:51:05] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:51:20] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:51:35] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:51:48] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:52:05] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:52:19] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:52:30] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:52:39] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:52:55] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:53:02] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:53:08] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:53:29] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:53:44] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:54:08] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:54:09] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:55:04] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:55:30] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:56:03] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:57:25] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 14:59:04] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 15:00:10] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 15:00:34] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 15:03:14] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 15:03:27] \"POST /upload HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/Apr/2025 15:15:01] \"POST /upload HTTP/1.1\" 200 -\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import pickle\n",
    "import cv2\n",
    "import numpy as np\n",
    "import torch\n",
    "import torchvision.transforms as transforms\n",
    "from flask import Flask, request, jsonify, send_file\n",
    "from PIL import Image\n",
    "\n",
    "app = Flask(__name__, static_folder=\"../frontend\", template_folder=\"../frontend\")\n",
    "\n",
    "# Paths\n",
    "BASE_DIR = os.getcwd()\n",
    "MODEL_DIR = os.path.join(BASE_DIR, \"..\", \"models\")\n",
    "FRONTEND_FILE = os.path.join(BASE_DIR, \"..\", \"frontend\", \"index.html\")\n",
    "UPLOAD_FOLDER = os.path.join(BASE_DIR, \"uploads\")\n",
    "\n",
    "# Ensure required folders exist\n",
    "if not os.path.exists(UPLOAD_FOLDER):\n",
    "    os.makedirs(UPLOAD_FOLDER)\n",
    "\n",
    "# Load trained SVM model for food classification\n",
    "model_path = os.path.join(MODEL_DIR, \"svm_model.pkl\")\n",
    "if not os.path.exists(model_path):\n",
    "    raise FileNotFoundError(f\"? Model not found at {model_path}\")\n",
    "\n",
    "print(f\"? Loading SVM model from {model_path}\")\n",
    "with open(model_path, \"rb\") as f:\n",
    "    svm_model = pickle.load(f)\n",
    "\n",
    "# Load ResNet18 for feature extraction\n",
    "print(\"? Loading ResNet18 model for feature extraction\")\n",
    "resnet18 = torch.hub.load(\"pytorch/vision:v0.10.0\", \"resnet18\", pretrained=True)\n",
    "resnet18.fc = torch.nn.Identity()\n",
    "resnet18.eval()\n",
    "\n",
    "# Image preprocessing\n",
    "transform = transforms.Compose([\n",
    "    transforms.Resize((224, 224)),\n",
    "    transforms.ToTensor(),\n",
    "    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])\n",
    "])\n",
    "\n",
    "# Food depth values (cm) for volume estimation\n",
    "food_depth = {\n",
    "    \"Bread\": 4, \"Dairy Product\": 5, \"Dessert\": 3, \"Egg\": 5,\n",
    "    \"Fried Food\": 6, \"Meat\": 7, \"Noodles-Pasta\": 4, \"Rice\": 3,\n",
    "    \"Seafood\": 5, \"Soup\": 2, \"Vegetable-Fruit\": 3\n",
    "}\n",
    "\n",
    "# Calorie values per cm�\n",
    "food_calories = {\n",
    "    \"Bread\": 2.5, \"Dairy Product\": 3.2, \"Dessert\": 4.0, \"Egg\": 1.5,\n",
    "    \"Fried Food\": 4.5, \"Meat\": 2.5, \"Noodles-Pasta\": 3.5, \"Rice\": 2.0,\n",
    "    \"Seafood\": 1.8, \"Soup\": 1.0, \"Vegetable-Fruit\": 0.8\n",
    "}\n",
    "\n",
    "# Vitamin content per food category\n",
    "food_vitamins = {\n",
    "    \"Bread\": [\"B1\", \"B2\", \"Niacin\"],\n",
    "    \"Dairy Product\": [\"Vitamin D\", \"Calcium\"],\n",
    "    \"Dessert\": [\"B2\", \"Folate\"],\n",
    "    \"Egg\": [\"Vitamin D\", \"B12\"],\n",
    "    \"Fried Food\": [\"None\"],\n",
    "    \"Meat\": [\"Iron\", \"B12\"],\n",
    "    \"Noodles-Pasta\": [\"B1\", \"B2\"],\n",
    "    \"Rice\": [\"None\"],\n",
    "    \"Seafood\": [\"Omega-3\", \"B12\"],\n",
    "    \"Soup\": [\"Vitamin A\", \"Vitamin C\"],\n",
    "    \"Vegetable-Fruit\": [\"Vitamin C\", \"Vitamin A\"]\n",
    "}\n",
    "\n",
    "@app.route(\"/\")\n",
    "def home():\n",
    "    return send_file(FRONTEND_FILE)\n",
    "\n",
    "@app.route(\"/upload\", methods=[\"POST\"])\n",
    "def upload():\n",
    "    if \"image\" not in request.files:\n",
    "        return jsonify({\"error\": \"No image file uploaded.\"})\n",
    "\n",
    "    file = request.files[\"image\"]\n",
    "    image_path = os.path.join(UPLOAD_FOLDER, file.filename)\n",
    "    file.save(image_path)\n",
    "\n",
    "    try:\n",
    "        # ?? Step 1: Extract Features for SVM Classification\n",
    "        image = Image.open(image_path).convert(\"RGB\")\n",
    "        image_tensor = transform(image).unsqueeze(0)\n",
    "\n",
    "        with torch.no_grad():\n",
    "            feature_vector = resnet18(image_tensor).numpy().flatten()\n",
    "\n",
    "        # ?? Step 2: Classify Food Using SVM\n",
    "        food_labels = list(food_depth.keys())\n",
    "        prediction = svm_model.predict([feature_vector])[0]\n",
    "        food_label = food_labels[prediction] if prediction in range(len(food_labels)) else \"Unknown Food\"\n",
    "\n",
    "        # ?? Step 3: Estimate Food Volume & Calories\n",
    "        depth = food_depth.get(food_label, 3)  # Default depth if missing\n",
    "        realistic_food_area = 40  # Fixed food area to prevent overestimation\n",
    "        volume_cm3 = realistic_food_area * depth\n",
    "        calories_per_cm3 = food_calories.get(food_label, 2.0)\n",
    "        estimated_calories = volume_cm3 * calories_per_cm3\n",
    "        vitamins = food_vitamins.get(food_label, [])\n",
    "\n",
    "        return jsonify({\n",
    "            \"food_category\": food_label,\n",
    "            \"image_url\": f\"/uploads/{file.filename}\",\n",
    "            \"calories_per_cm3\": calories_per_cm3,\n",
    "            \"estimated_calories_kcal\": round(estimated_calories, 2),\n",
    "            \"vitamins\": vitamins\n",
    "        })\n",
    "\n",
    "    except Exception as e:\n",
    "        return jsonify({\"error\": f\"Prediction failed: {str(e)}\"})\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    app.run(debug=True, use_reloader=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5dc557c6-2706-4330-83e2-04987e60f238",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
